[extend]
useDefault = true

[allowlist]
paths = [
  '''(^|/)node_modules(/|$)''',
  '''(^|/)\.git(/|$)''',
  '''(^|/)\.next(/|$)''',
  '''(^|/)dist(/|$)''',
  '''(^|/)build(/|$)''',
  '''(^|/)out(/|$)''',
  '''(^|/)coverage(/|$)''',
]
